Brand these dotfiles as DotFriedRice
After 8 years of maintaining these dotfiles, this is one of the few
breaking changes that's been introduced, but you can get everything
updated in a few commands and quick surgical edits.

If you've previously installed my dotfiles, migrate by running:

Run ./install --pull , to get the latest files
Rename your local directory from dotfiles to dotfriedrice
Update your .git/config to replace dotfiles with dotfriedrice everywhere
Run ./dotfriedrice diff-config , and update env vars that need changing
Run ./dotfriedrice -S , to update all of the configs and symlinks
Edit your .zprofile.local file to remove the old DOTFILES_PATH

You're best off rebooting or at least logging out and back in to have
everything new take effect since we modified an env var in your zprofile
which only gets sourced once upon login.

Besides that, the ./install script has been replaced with ./dotfriedrice
and most of the flags are now sub-commands instead. This sets up for a
potentially more in-depth CLI tool in the future.

diff --git a/.local/bin/dfr-launch-or-focus-tui b/.local/bin/dfr-launch-or-focus-tui
--- a/.local/bin/dfr-launch-or-focus-tui
+++ b/.local/bin/dfr-launch-or-focus-tui
@@ -1,9 +1,8 @@
 #!/usr/bin/env bash
-# Launch or focus an already running app by shortname or reverse DNS identifier.
+# Launch or focus an already running TUI by binary name.
 #
 # Examples:
-#   dot-launch-or-focus ghostty [ARGS]
-#   dot-launch-or-focus com.mitchellh.ghostty [ARGS]
+#   dfr-launch-or-focus-tui btop [ARGS]
 
 set -o errexit
 set -o pipefail
@@ -29,14 +28,15 @@ APP_ID=$(
 )
 
 if [ "${APP_ID}" == "null" ]; then
+  if ! command -v "${APP}" >/dev/null 2>&1; then
+    echo "${APP} does not exist, aborting!" >&2
+    exit 1
+  fi
+
   # We shift here so that $@ has all of the arguments but not the app name.
   shift
 
-  # APP supports the shortname (ghostty) and reverse DNS id (com.mitchellh.ghostty)
-  # so let's extract the last segment using . to split on.
-  SPAWN_APP="${APP##*.}"
-
-  niri msg action spawn -- "${SPAWN_APP}" "$@"
+  niri msg action spawn -- ghostty --class="dfr.ghostty.${APP}" -e "${APP}" "$@"
 else
   niri msg action focus-window --id "${APP_ID}"
 fi
