Switch from Paru to Yay for AUR management
Arch is a rolling release and an underlying Rust package was updated to
a newer version which has broken Paru for a few days.

Long story short, I'm going to give Yay a try. I initially picked Paru
because it easily showed diffs for PKGBUILD files which felt responsible
to do before running build scripts on your system from untrusted sources.

Fortunately you can get similar results with Yay.

diff --git a/.local/bin/pkg b/.local/bin/pkg
--- a/.local/bin/pkg
+++ b/.local/bin/pkg
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-# Manage packages using Pacman (Arch) and Paru (AUR) repositories.
+# Manage packages using Pacman (Arch) and Yay (AUR) repositories.
 
 set -o errexit
 set -o pipefail
@@ -28,13 +28,13 @@ Usage examples:
   ^ pacman -Syu --needed
 
   pkg install --aur    # Install / search new AUR packages
-  ^ paru -Syu --needed
+  ^ yay -S --needed
 
   pkg list             # List locally installed packages
   ^ pacman -Qei
 
   pkg list --aur       # List locally installed AUR packages
-  ^ paru -Qm
+  ^ yay -Qm
 
   pkg remove           # Remove installed packages
   ^ pacman -Rns
@@ -125,19 +125,19 @@ install_aur() {
 
   local query packages=
 
-  read -rp "Enter AUR search query (at least 2 characters): " query
+  read -rp "Enter AUR search query (at least 3 characters): " query
 
-  if [[ ${#query} -lt 2 ]]; then
-    echo "'${query}' must be 2 or more characters, aborting!" >&2
+  if [[ ${#query} -lt 3 ]]; then
+    echo "'${query}' must be 3 or more characters, aborting!" >&2
     exit 1
   fi
 
   # shellcheck disable=SC2016
   mapfile -t fzf_opts \
-    < <(fzf_args "Filter AUR packages to install..." 'paru -Si $(echo {} | cut -d " " -f 1)' "tiebreak")
+    < <(fzf_args "Filter AUR packages to install..." 'yay -Si $(echo {} | cut -d " " -f 1)' "tiebreak")
 
   packages="$(
-    paru -Ssa "$query" | awk '
+    yay -Ssa "$query" | awk '
       /^[^ ]/ {
         split($1, a, "/")
         pkg = a[2]
@@ -154,9 +154,10 @@ install_aur() {
 
   if [ -n "${packages}" ]; then
     # shellcheck disable=SC2086
-    paru -Syu --needed ${packages}
+    yay -S --answerclean N --needed ${packages}
   fi
 }
+
 list() {
   local packages=
 
@@ -181,13 +182,13 @@ list_aur() {
 
   # shellcheck disable=SC2016
   mapfile -t fzf_opts \
-    < <(fzf_args "Search installed AUR packages..." 'paru -Qi $(echo {} | cut -d" " -f1)' "tiebreak")
+    < <(fzf_args "Search installed AUR packages..." 'yay -Qi $(echo {} | cut -d" " -f1)' "tiebreak")
 
   packages="$(
-    paru -Qm | awk '
+    yay -Qm | awk '
     {
       pkg = $1
-      cmd = "paru -Qi " pkg " 2>/dev/null | grep -m1 \"^Description\""
+      cmd = "yay -Qi " pkg " 2>/dev/null | grep -m1 \"^Description\""
       desc = ""
       if ((cmd | getline line) > 0) {
         sub(/^[^:]*:\s*/, "", line)
@@ -228,15 +229,15 @@ remove_aur() {
 
   # shellcheck disable=SC2016
   mapfile -t fzf_opts \
-    < <(fzf_args "Search installed AUR packages to remove..." 'paru -Qi $(echo {} | cut -d " " -f 1)' "tiebreak")
+    < <(fzf_args "Search installed AUR packages to remove..." 'yay -Qi $(echo {} | cut -d " " -f 1)' "tiebreak")
 
   # This is the same code as listing from the AUR plus an added cut pipe. This
   # could be refactored at some point, for now it's not the end of the world.
   packages="$(
-    paru -Qm | awk '
+    yay -Qm | awk '
     {
       pkg = $1
-      cmd = "paru -Qi " pkg " 2>/dev/null | grep -m1 \"^Description\""
+      cmd = "yay -Qi " pkg " 2>/dev/null | grep -m1 \"^Description\""
       desc = ""
       if ((cmd | getline line) > 0) {
         sub(/^[^:]*:\s*/, "", line)
